version: '3.1'

volumes:
  postgres:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - C:\git\docker\piv-dev-docker\pg:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
