version: '10.3'

services:
    weblogic10.3:
        image: vulhub/weblogic
        container_name: weblogic10.3
        networks:
            - testNetWork
        ports:
            - 7001:7001
            - 8453:8453
            - 9999:9999
        volumes:
            - ./dockerShare:/dockerShare
        tty: true
networks:
    testNetWork:
        external: true
