version: '10.3'

services:
    weblogic:
        image: ismaleiva90/weblogic12:latest
        container_name: weblogic
        networks:
            - testNetWork
        ports:
            - 7001:7001
            - 8453:8453
            - 9999:9999
        volumes:
            - ./dockerShare:/dockerShare
        tty: true
networks:
    testNetWork:
        external: true
