CREATE ROLE piv WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;
ALTER USER reb password 'PIV';

CREATE ROLE reb WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;
ALTER USER reb password 'REB';
  
CREATE ROLE isum12 WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;
ALTER USER isum12 password 'ISUM12';