version: '3.1'

volumes:
  postgres:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    user: '1000:1000'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./tablespace:/var/lib/postgresql/tablespace:rw
      - ./scripts/role.sql:/docker-entrypoint-initdb.d/role.sql
      - ./scripts/tablespace.sql:/docker-entrypoint-initdb.d/tablespace.sql
    ports:
      - ${POSTGRES_PORT:-5432}:5432
