version: '3.1'

volumes:
  postgres:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/opt/postgres/data:rwx
      - ./scripts:/opt/postgres/scripts:rwx
    ports:
      - ${POSTGRES_PORT:-5432}:5432