version: '3.1'

volumes:
  postgres:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data:rw
      - ./scripts:/var/lib/postgresql/scripts
    ports:
      - ${POSTGRES_PORT:-5432}:5432